In [2]:
'Shit + Enter'

'Shit + Enter'

In [5]:
array=[1,23]

In [1]:
print('dinesh')

dinesh


In [6]:
print('come on dinesh')

come on dinesh


In [7]:
import numpy as np

my_list=[1,2,3]

In [ ]:
arr = np.array(my_list)

In [39]:
arr

array([1, 2, 3])

In [11]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [12]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [15]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [16]:
identitymatrix = np.eye(4)

In [17]:
identitymatrix

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [18]:
randomnum=np.random.rand(5)

In [19]:
randomnum

array([ 0.71507322,  0.89930903,  0.32928968,  0.50407665,  0.50219632])

In [20]:
normaldistrubution = np.random.randn(5)

In [21]:
randominteger=np.random.randin(1,100,5)

AttributeError: module 'numpy.random' has no attribute 'randin'

In [22]:
randomintegers=np.random.randn(1,100,10)

In [23]:
randonintegers

NameError: name 'randonintegers' is not defined

In [24]:
randomintegers

array([[[ -1.76013540e-01,   6.93252738e-01,   2.21356788e+00,
          -1.96900205e-01,   1.49492159e+00,   3.79879932e-01,
           2.68626792e-01,   6.87093295e-01,   2.31515129e-01,
           5.57485442e-02],
        [ -3.69203573e-01,  -7.21536893e-01,  -1.51764377e-01,
          -3.16850877e-02,  -1.25628562e+00,  -1.89042160e-01,
           8.62947947e-01,  -1.69915463e+00,   3.21510266e-01,
          -4.46845455e-01],
        [  7.16049114e-01,  -4.69808170e-01,  -7.31616178e-01,
           9.03798088e-01,  -2.79462459e-01,  -1.03158550e+00,
           1.05291147e-01,  -9.07236995e-01,   9.14643706e-02,
          -5.18021565e-01],
        [  7.00687070e-01,  -2.82732243e-01,   1.10499079e+00,
          -4.10563050e-01,   1.31189674e+00,   4.81487369e-01,
           1.72641892e+00,  -1.03802595e+00,  -1.76488424e+00,
           1.38763017e+00],
        [  5.23577255e-01,  -2.72696346e+00,  -2.26900769e+00,
           4.10976295e-01,   2.42587093e+00,   1.27513374e+00,
      

In [25]:
randomintegers=np.random.randint(1,101,10)

In [26]:
randomintegers

array([76,  5, 42, 66, 12, 69, 38, 78, 74, 67])

In [28]:
twentyfivearrange= np.arange(25)

In [29]:
twentyfivearrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
len(twentyfivearrange)

25

In [31]:
twentyfivearrange.reshape(5,6)

ValueError: cannot reshape array of size 25 into shape (5,6)

In [32]:
twentyfivearrange.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [33]:
twentyfivearrange.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
randomintegers.max()

78

In [35]:
randomintegers.argmin()

1

In [38]:
twentyfivearrange.shape
twentyfivearrange.dtype

dtype('int32')

In [40]:
normaldistrubution

array([-1.48056974,  0.99544135, -0.54794194, -0.27524936,  2.39046765])

In [41]:
arrayindexoper = np.arange(0,11)

In [42]:
arrayindexoper[1:5]

array([1, 2, 3, 4])

In [43]:
arrayindexoper

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arrayindexoper[:6]

array([0, 1, 2, 3, 4, 5])

In [46]:
arrayindexoper[11:]

array([], dtype=int32)

In [47]:
arrayindexoper[0:5]=100

In [48]:
arrayindexoper

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [49]:
arrayindexoper=np.arange(0,11)

In [50]:
slice_of_arr=arrayindexoper[0:6]

In [51]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [52]:
slice_of_arr[:]=27

In [53]:
arrayindexoper

array([27, 27, 27, 27, 27, 27,  6,  7,  8,  9, 10])

In [54]:
array_copy= arrayindexoper.copy()

In [56]:
array_copy[:]=3

In [57]:
array_copy

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [58]:
arrayindexoper

array([27, 27, 27, 27, 27, 27,  6,  7,  8,  9, 10])

In [ ]:
arrayindexoper